# Generated by Django 4.1.3 on 2023-01-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_notifications_historicalnotifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalquestions",
            name="preview",
            field=models.TextField(default="0", verbose_name="Превью"),
        ),
        migrations.AddField(
            model_name="questions",
            name="preview",
            field=models.TextField(default="0", verbose_name="Превью"),
        ),
    ]
