# Generated by Django 4.1.3 on 2023-01-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_historicalquestions_preview_questions_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalquestions",
            name="preview",
            field=models.TextField(verbose_name="Превью"),
        ),
        migrations.AlterField(
            model_name="questions",
            name="preview",
            field=models.TextField(verbose_name="Превью"),
        ),
    ]
