# Generated by Django 4.1.3 on 2023-01-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_historicalquestions_preview_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaluser",
            old_name="name",
            new_name="username",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="username",
        ),
        migrations.RemoveField(
            model_name="historicaluser",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="id",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
