# Generated by Django 4.1.3 on 2023-01-13 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_premiumuser_historicalpremiumuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpremiumuser",
            name="level",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="premiumuser",
            name="level",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="premiumuser",
            name="id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="main.user",
                unique=True,
            ),
        ),
    ]
